version: '3.8'

services:
  user_service:
    build:
      context: ./user_service  # Путь к каталогу с Dockerfile для user_service
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:rongal1000@host.docker.internal:5432/user  # Подключение к внешней базе данных

  product_service:
    build:
      context: ./product_service  # Путь к каталогу с Dockerfile для product_service
    ports:
      - "8001:8001"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:rongal1000@host.docker.internal:5432/product  # Подключение к внешней базе данных

  order_service:
    build:
      context: ./order_service  # Путь к каталогу с Dockerfile для order_service
    ports:
      - "8002:8002"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:rongal1000@host.docker.internal:5432/order  # Подключение к внешней базе данных

  cart_service:
    build:
      context: ./cart_service  # Путь к каталогу с Dockerfile для cart_service
    ports:
      - "8003:8003"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:rongal1000@host.docker.internal:5432/cart  # Подключение к внешней базе данных

  stock_service:
    build:
      context: ./stock_service  # Путь к каталогу с Dockerfile для stock_service
    ports:
      - "8004:8004"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:rongal1000@host.docker.internal:5432/stock  # Подключение к внешней базе данных

networks:
  backend:
    driver: bridge
